"""Add households.

Revision ID: a007ea0f5b49
Revises: 9803aa3cdf32
Create Date: 2026-06-27 03:22:33.269884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a007ea0f5b49'
down_revision: Union[str, Sequence[str], None] = '9803aa3cdf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'household_id')
    )
    op.drop_index(op.f('ix_shopping_items_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_constraint(op.f('users_household_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'household_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('household_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_household_id_fkey'), 'users', 'households', ['household_id'], ['id'])
    op.create_table('shopping_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_purchased', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('household_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('shopping_items_added_by_id_fkey')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('shopping_items_household_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shopping_items_pkey'))
    )
    op.create_index(op.f('ix_shopping_items_id'), 'shopping_items', ['id'], unique=False)
    op.drop_table('household_members')
    # ### end Alembic commands ###
