name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate .env file
        run: |
          cat << 'EOF' > .env
          ${{secrets.ENV_FILE_CONTENTS}}
          EOF
      - name: Start and Update Containers
        run: make prod
      - name: Run Database Migrations
        run: make migrate
      - name: Restart Nginx Proxy Manager
        run: make restart-nginx
      - name: Clean up old Docker resources
        run: make clean
