name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy Production Stack
        run: |
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
          docker system prune -f
